Only pass str paths to tarfile; unicode causes trouble
Typical error:

Traceback (most recent call last):
  File "./0export", line 229, in <module>
    setup_tar.add(impl, 'implementations/' + os.path.basename(impl))
  File "/usr/lib/python2.5/tarfile.py", line 1475, in add
    self.addfile(tarinfo, f)
  File "/usr/lib/python2.5/tarfile.py", line 1499, in addfile
    self.fileobj.write(buf)
  File "/usr/lib/python2.5/tarfile.py", line 402, in write
    self.__write(s)
  File "/usr/lib/python2.5/tarfile.py", line 408, in __write
    self.buf += s
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf9 in position 0: ordinal not in range(128)